server:
    port: 8080

spring:
    application:
        name: zuul-server


eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
    serviceurl:
        defaultzone: http://localhost:8761/eureka/

zuul:
    routes:
        preduzece:
            path: /api/preduzece/**
            serviceId:  preduzece

management:
    endpoints:
        web:
            exposure:
                include: "*"